repos:
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.31.0
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: V2.7.1  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
        types_or: [css, javascript, html, vue]